version: '3.8'

services:
  auth:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: auvet-auth-prod
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - PORT=4000
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=24h
    networks:
      - auvet-backend_auvet-network-prod

networks:
  auvet-backend_auvet-network-prod:
    external: true

